export const editRadioClickModal={
    audit_call_done: "",
    audit_call_done_remark:"",
    audit_call_status: "",
    audit_call_status_remark:"",
    audit_case_status_id:"" ,
    audit_case_status_remark:"",
    status:"",
    remark:"",
}
 export const updateRadioClickModal={
    reasonNotFound:"",
    addressRemark:"",
    nearLandmark:"",
    candidateState:"",
    verifyBy:"",
    relationType:"",
    relationTypeMeetPerson:"",
    meetPersonContactNo:"",
    idProof:"",
    fromDate:"",
    toDate:"",
    stayVerification:"",
    residenceStatus:"",
    residenceType:"",
    areaType:"",
    additionalRemark:"",
    additionalRemarkByFE:"",
    verificationRemarkByFE:"",
    verificationDoneDate:"",
    FE:"",
    address:"",
    FESignature:"",
    candidateSignature:""
    }

export const updateRadioUnviewModal={
    additionalRemarkFA:"",
    FE:"",
    verificationRemark:"",
    statusVerification:"",
    buildingPhotoStatus:"",
    buildingPhotoRemark:"",
    addressProofStatus:"",
    addressProofRemark:"",
    landmarkPhotoStatus:"",
    landmarkPhotoRemark:"",
    fromDate:"",
    toDate:"",
    contactNoRelative:"",
    verificationDate:"",
    verificationTime:"",
    residenceStatus:"",
    residenceType:"",
    verifyByRespondent:"",
    relationWithCandidate:"",
    nearLandmark:"",
}
