export const editRadioClickModal={
    auditCallDone: "",
    auditCallDoneRemark:"",
    auditCallStatus: "",
    auditCallStatusRemark:"",
    auditCaseStatusId:"" ,
    auditCaseStatusRemark:"",
    status:"",
    remark:"",
}

 export const updateRadioClickModal={
    reasonNotFound:"",
    addressRemark:"",
    nearLandmark:"",
    candidateState:"",
    verifyBy:"",
    relationType:"",
    relationTypeMeetPerson:"",
    meetPersonContactNo:"",
    idProof:"",
    fromDate:"",
    birthCheckForm:"",
    tillCheckForm:"",
    toDate:"",
    stayVerification:"",
    residenceStatus:"",
    residenceType:"",
    areaType:"",
    additionalRemark:"",
    additionalRemarkByFEForm:"",
    verificationRemarkByFE:"",
    verificationDoneDate:"",
    FE:"",
    address:"",
    FESignature:"",
    candidateSignature:""
    }

export const updateRadioUnviewModal={
    additionalRemarkFA:"",
    FE:"",
    verificationRemarkForm:"",
    statusVerification:"",
    buildingPhotoStatus:"",
    buildingPhotoRemark:"",
    addressProofStatus:"",
    addressProofRemark:"",
    landmarkPhotoStatus:"",
    landmarkPhotoRemark:"",
    fromDate:"",
    toDate:"",
    contactNoRelative:"",
    verificationDate:"",
    verificationTime:"",
    residenceStatus:"",
    residenceType:"",
    verifyByRespondent:"",
    relationWithCandidate:"",
    nearLandmark:"",
}
