export const appStatusData=[
    {
        id:1,
        appStatus:"under_admin"
    },
    {
        id:2,
        appStatus:"verify_by_admin"
    },
    {
        id:3,
        appStatus:"rejected_by_admin"
    },
    {
        id:4,
        appStatus:"under_employee"
    },
    {
        id:5,
        appStatus:"verify_by_employee"
    },
    {
        id:6,
        appStatus:"rejected_by_employee"
    },
    {
        id:7,
        appStatus:"under_FE"
    },
    {
        id:8,
        appStatus:"verify_by_FE"
    },
    {
        id:9,
        appStatus:"rejected_by_FE"
    },
    {
        id:10,
        appStatus:"complete"
    },
    {
        id:11,
        appStatus:"withdraw"
    },
    {
        id:12,
        appStatus:"close"
    }
]