export const verificationModalVarData=[
    {
        id:"",
        checkId:"",
        companyId:"", 
        candidateName:"", 
        fatherName:"",
        contactNo:"",
        alternateNo:"", 
        alternateNo2:"",
        verificationType:"",
        address:"",
        city:"",
        district:"",
        state:"",
        pincode:"",
        EMP:" ",
        FE:"",
        clientName:"", 
        resumeId:"",
        landmark:"",
        audit_call_done: "",
        audit_call_done_remark:"",
        audit_call_status: "",
        audit_call_status_remark:"",
        audit_case_status_id:"" ,
        audit_case_status_remark:"",
        status:"",
        remark:"",
        durationStart:"",
        durationEnd:"", 
        assignedTo:"", 
        assignedBy:"", 
        email:"",
    }
]